# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x1cmarket_data_processor.protos\"x\n\tQuoteData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tbid_price\x18\x03 \x01(\x01\x12\x11\n\task_price\x18\x04 \x01(\x01\x12\x10\n\x08\x62id_size\x18\x05 \x01(\x05\x12\x10\n\x08\x61sk_size\x18\x06 \x01(\x05\"`\n\tTradeData\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0e\n\x06volume\x18\x04 \x01(\x05\x12\x11\n\tcondition\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUOTEDATA']._serialized_start=51
  _globals['_QUOTEDATA']._serialized_end=171
  _globals['_TRADEDATA']._serialized_start=173
  _globals['_TRADEDATA']._serialized_end=269
# @@protoc_insertion_point(module_scope)
